AWSTemplateFormatVersion: "2010-09-09"
#Base case one primary key
Description: >
  central-sre-security-hub-cfn dynamo template version: v0.0.1
  Enforces: security hub rule(s) 
  - DYDB01
  - DYDB02
  - DYDB09
  - DYDB10
  - ADR 0134
  - DYDB03 
  - DYDB04 
  - DYDB05
  - DYDB11
  - SCRTS01
  - SCRTS03
  - SCRTS05.
  Supports: security hub rule(s) SCRTS04. 
  Managed by: central-sre.

Parameters:
  #Add a naming convention here
  DynamoTableName:
    Description: "What is the name of your table? The default naming convention is Owner-Environment-System."
    Default: "null"
    Type: String

  ContributorInsightsEnabled:
    Description: "Do you want to enable Cloudwatch Contributor Insights?"
    Default: false
    Type: String
    AllowedValues:
       - true
       - false

  TableKMSKey:
    Description: "It is manitory to provide a KMS key ID to encrypt this table at rest. This ID must exist in the account which you are deploying to."
    Type: String

  ProvisionedThroughputEnabled:
    Description: "Do you want to enable the database to be run in provisioned throughput mode?"
    Default: false
    Type: String
    AllowedValues:
         - true
         - false

  # Dynamo Naturally throttles reads on 40k per table and 80k per account
  ReadCapacityUnits:
    Description: "The maximum number of strongly consistent reads consumed per second before DynamoDB returns a ThrottlingException."
    Type: Number
    Default: 300
    MinValue: 100
    MaxValue: 20000 

  # Dynamo Naturally throttles writes on 40k per table and 80k per account
  WriteCapacityUnits: 
    Description: "The maximum number of writes consumed per second before DynamoDB returns a ThrottlingException."
    Type: Number
    Default: 300  
    MinValue: 100 
    MaxValue: 20000 

  PrimaryKeyName:
    Description: "The Name of your primary key for the table."
    Type: String
    Default: "id"
    MinLength: 1
    MaxLength: 255

  PrimaryKeyType:
    Description: "The type of your primary key. Must be either S (String), N (Number), or B (Boolean)."
    Type: String
    Default: "S"
    AllowedValues:
         - "S"
         - "N"
         - "B"
  
  TimeToLiveEnabled:
    Type: String
    Default: true
    Description: "Do you want to enable time to live for this table?"
    AllowedValues:
      - true
      - false

  TimeToLiveColumnName:
    Type: String
    Default: "TTL"
    Description: "Name of the time to live column."

  PointInTimeRecoveryEnabled:
    Type: String
    Default: true
    Description: "Do you want to enable point in time recovery?"
    AllowedValues:
      - true
      - false

  Product:
    Type: String
    Default: GOV.UK
    Description: "Tag all your resources with the product name."

  System:
    Type: String
    Default: Central SRE - test service
    Description: "Tag all your resources with the service name."

  Environment:
    Type: String
    Default: dev
    Description: "Tag the environment to all your resources."

  Owner:
    Type: String
    Default: Central SRE
    Description: "Tag all your resources with the team name."

Conditions:
  IsProvisionedThroughputEnabled: !Equals [true, !Ref ProvisionedThroughputEnabled]
  HasTableName: !Not [!Equals ["null", !Ref DynamoTableName]]

Resources:
  DynamoDB:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: !Ref PrimaryKeyName
          AttributeType: !Ref PrimaryKeyType
      ContributorInsightsSpecification:
        Enabled: !Ref ContributorInsightsEnabled
      KeySchema:
        - AttributeName: !Ref PrimaryKeyName
          KeyType: "HASH"
      BillingMode: !If [IsProvisionedThroughputEnabled, "PROVISIONED", "PAY_PER_REQUEST"]
      ProvisionedThroughput: !If
        - IsProvisionedThroughputEnabled
        -
          ReadCapacityUnits: !Ref ReadCapacityUnits
          WriteCapacityUnits: !Ref WriteCapacityUnits
        - !Ref "AWS::NoValue"
      TableName: !If [HasTableName, !Ref DynamoTableName, !Sub "${Owner}-${Environment}-${System}"]
      TimeToLiveSpecification:
        AttributeName: !Ref TimeToLiveColumnName
        Enabled: !Ref TimeToLiveEnabled
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !Ref PointInTimeRecoveryEnabled
      SSESpecification:
        KMSMasterKeyId: !Ref TableKMSKey
        SSEEnabled: true
        SSEType: KMS
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}"
        - Key: Product
          Value: !Ref Product
        - Key: System
          Value: !Ref System
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref Owner

Outputs:
  TableName:
    Description: "The name of the DynamoDB table"
    Value: !Ref DynamoDB
    Export:
      Name: !Sub "${AWS::StackName}-table-name"
  TableArn:
    Description: "The Arn of the DynamoDB table"
    Value: !GetAtt DynamoDB.Arn
    Export:
      Name: !Sub "${AWS::StackName}-table-arn"
  TableKeyId:
    Description: "The Id of the Events table encryption key"
    Value: !Ref TableKMSKey
    Export:
      Name: !Sub "${AWS::StackName}-dynamo-key-id"
      
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: "Manditory Tags"
        Parameters: 
          - Product
          - System
          - Environment
          - Owner