general:
  s3_bucket: "di-central-sre-build-taskcat"
  regions:
   - eu-west-2

project:
  owner: di-central-sre-build
  name: security-hub-template-tests
  package_lambda: false
  

  # OPTIONAL: create a bucket for taskcat to use if you don't want it to generate a new one everytime it is run

  
tests:
  test-secrets-manager:
    parameters:
      SecretName: taskcat-secret
      SecretDescription: "A secret tested by taskcat"
      PeriodicRotationDays: 90
      KeyRotationLambdaARN: arn:aws:lambda:eu-west-2:891376909120:function:fakeSecretRotate
      KmsKeyId: 88564c70-2d7f-4781-b6a2-c1e10f62692c
      NotifyAfterUnusedForDays: 90
    template: ./cloudformation/secrets-manager/template.yaml
    

  test-another-secrets-manager:
    parameters:
      SecretName: another-taskcat-secret
      SecretDescription: "A different secret tested by taskcat"
      PeriodicRotationDays: 90
      KeyRotationLambdaARN: arn:aws:lambda:eu-west-2:891376909120:function:fakeSecretRotate
      KmsKeyId: 88564c70-2d7f-4781-b6a2-c1e10f62692c
      NotifyAfterUnusedForDays: 90
    template: ./cloudformation/secrets-manager/template.yaml
   