general:
  s3_bucket: "di-central-sre-build-taskcat"
  regions:
   - eu-west-2
  artifact_regions:
    - eu-west-2
  tags:
      TestingFramework: taskcat-<hash-place-holder>

project:
  owner: di-central-sre-build
  name: security-hub-template-tests
  package_lambda: false
  
tests:

  # encryption
  test-kms:
    parameters:
      System: taskcat-<hash-place-holder>
      DeletionPolicy: Delete
      UpdateReplacePolicy: Delete
    template: ./service_catalog_portfolios/encryption/kms/template.yaml

  # messaging
  # test-sns:
  #   parameters:
  #     TopicName: taskcat-<hash-place-holder>
  #     KMSKeyId: 31dc9883-64a5-43f9-86b4-ef0f929e3343
  #     System: taskcat-<hash-place-holder>
  #   template: ./service_catalog_portfolios/messaging/sns/template.yaml

  # test-sns-subscription:
  #   parameters:
  #     TopicArn: arn:aws:sns:eu-west-2:891376909120:taskcat-topic
  #     SubscriberArn: arn:aws:lambda:eu-west-2:891376909120:function:sc-product-test-empty-lambda-LambdaFunction-NX8tjZ3sq0PX
  #     System: taskcat-<hash-place-holder>
  #   template: ./service_catalog_portfolios/messaging/sns-subscription/template.yaml

  # # storage
  # ## dynamodb
  # test-dynamodb:
  #   parameters:
  #     DynamoTableName: Taskcat-<hash-place-holder>-table
  #     TableKMSKey: 31dc9883-64a5-43f9-86b4-ef0f929e3343
  #     System: taskcat-<hash-place-holder> 
  #     DeletionPolicy: Delete
  #     UpdateReplacePolicy: Delete
  #   template: ./service_catalog_portfolios/storage/dynamo/template.yaml

  # ## s3
  # s3-elb-access-logs-bucket:
  #   parameters:
  #     S3BucketName: taskcat-<hash-place-holder>-secret
  #     ELBAccessLogsBucketName: taskcat-<hash-place-holder>-logs
  #     S3ServerAccessLogsBucket: di-central-sre-build-access-logs
  #     System: taskcat-<hash-place-holder>
  #     DeletionPolicy: Delete
  #     UpdateReplacePolicy: Delete
  #   template: ./service_catalog_portfolios/storage/s3/elb-access-logs-bucket.yaml

  # test-logging-bucket:
  #   parameters:
  #     S3BucketName: taskcat-<hash-place-holder>-secret
  #     System: taskcat-<hash-place-holder>
  #     DeletionPolicy: Delete
  #     UpdateReplacePolicy: Delete
  #   template: ./service_catalog_portfolios/storage/s3/s3-logging-bucket.yaml
  
  # ## secrets manager
  # test-secrets-manager:
  #   parameters:
  #     SecretName: taskcat-<hash-place-holder>-secret
  #     SecretDescription: "A secret tested by taskcat"
  #     KeyRotationLambdaARN: arn:aws:lambda:eu-west-2:891376909120:function:sc-product-test-empty-lambda-LambdaFunction-NX8tjZ3sq0PX
  #     KmsKeyId: 31dc9883-64a5-43f9-86b4-ef0f929e3343
  #     NotifyAfterUnusedForDays: 90
  #     DeletionPolicy: Delete
  #     UpdateReplacePolicy: Delete
  #     System: taskcat-<hash-place-holder>
  #   template: ./service_catalog_portfolios/storage/secrets-manager/template.yaml