general:
  s3_bucket: "di-central-sre-build-taskcat"
  regions:
   - eu-west-2
  artifact_regions:
    - eu-west-2
  tags:
      TestingFramework: taskcat-<hash-place-holder>

project:
  owner: di-central-sre-build
  name: security-hub-template-tests
  package_lambda: false
  
tests:
  test-secrets-manager:
    parameters:
      SecretName: taskcat-<hash-place-holder>-secret
      SecretDescription: "A secret tested by taskcat"
      PeriodicRotationDays: 90
      KeyRotationLambdaARN: arn:aws:lambda:eu-west-2:891376909120:function:sc-product-test-empty-lambda-LambdaFunction-AZvc5k0e2IhP
      KmsKeyId: bdfc7df5-95ae-426b-b520-80c3d434ae52
      NotifyAfterUnusedForDays: 90
    template: ./service_catalog_portfolios/storage/secrets-manager/template.yaml
    

  # test-another-secrets-manager:
  #   parameters:
  #     SecretName: another-taskcat-secret
  #     SecretDescription: "A different secret tested by taskcat"
  #     PeriodicRotationDays: 90
  #     KeyRotationLambdaARN: arn:aws:lambda:eu-west-2:891376909120:function:fakeSecretRotate
  #     KmsKeyId: 88564c70-2d7f-4781-b6a2-c1e10f62692c
  #     NotifyAfterUnusedForDays: 90
  #   template: ./cloudformation/secrets-manager/template.yaml
   