general:
  s3_bucket: "di-central-sre-build-taskcat"
  regions:
   - eu-west-2
  artifact_regions:
    - eu-west-2
  tags:
      TestingFramework: taskcat-abc123

project:
  owner: di-central-sre-build
  name: security-hub-template-tests
  package_lambda: false
  
tests:

  # compute
  test-lambda:
    parameters:
      LambdaRole: iam-for-empty-lambda
      SubnetIds: subnet-0a1c19ce3ee6b2d50,subnet-0e2e55747c817abac
      SecurityGroupIds: "sg-05fa01fdf5d0dd615"
      SecretsManagerArn: arn:aws:secretsmanager:eu-west-2:891376909120:secret:terraform-20240222170217389100000001-yES23Q
      LambdaCodeUriBucket: di-central-sre-build-artifact
      LambdaCodeUriKey: python/empty-lambda.zip
      Runtime: python3.11
      LambdaHandler: handler.process
      System: taskcat-abc123
      LambdaRoleNamePrefix: ""
    template: ./service_catalog_portfolios/compute/lambda/sam-cfn-template.yaml

  # encryption
  # test-kms:
  #   parameters:
  #     System: taskcat-abc123
  #     DeletionPolicy: Delete
  #     UpdateReplacePolicy: Delete
  #   template: ./service_catalog_portfolios/encryption/kms/template.yaml

  # messaging
  # test-sns:
  #   parameters:
  #     TopicName: taskcat-abc123
  #     KMSKeyId: 31dc9883-64a5-43f9-86b4-ef0f929e3343
  #     System: taskcat-abc123
  #   template: ./service_catalog_portfolios/messaging/sns/template.yaml

  # test-sns-subscription:
  #   parameters:
  #     TopicArn: arn:aws:sns:eu-west-2:891376909120:taskcat-topic
  #     SubscriberArn: arn:aws:lambda:eu-west-2:891376909120:function:sc-product-test-empty-lambda-LambdaFunction-NX8tjZ3sq0PX
  #     System: taskcat-abc123
  #   template: ./service_catalog_portfolios/messaging/sns-subscription/template.yaml

  # # storage
  # ## dynamodb
  # test-dynamodb:
  #   parameters:
  #     DynamoTableName: Taskcat-abc123-table
  #     TableKMSKey: 31dc9883-64a5-43f9-86b4-ef0f929e3343
  #     System: taskcat-abc123 
  #     DeletionPolicy: Delete
  #     UpdateReplacePolicy: Delete
  #   template: ./service_catalog_portfolios/storage/dynamo/template.yaml

  # ## s3
  # s3-elb-access-logs-bucket:
  #   parameters:
  #     S3BucketName: taskcat-abc123-secret
  #     ELBAccessLogsBucketName: taskcat-abc123-logs
  #     S3ServerAccessLogsBucket: di-central-sre-build-access-logs
  #     System: taskcat-abc123
  #     DeletionPolicy: Delete
  #     UpdateReplacePolicy: Delete
  #   template: ./service_catalog_portfolios/storage/s3/elb-access-logs-bucket.yaml

  # test-logging-bucket:
  #   parameters:
  #     S3BucketName: taskcat-abc123-secret
  #     System: taskcat-abc123
  #     DeletionPolicy: Delete
  #     UpdateReplacePolicy: Delete
  #   template: ./service_catalog_portfolios/storage/s3/s3-logging-bucket.yaml
  
  # ## secrets manager
  # test-secrets-manager:
  #   parameters:
  #     SecretName: taskcat-abc123-secret
  #     SecretDescription: "A secret tested by taskcat"
  #     KeyRotationLambdaARN: arn:aws:lambda:eu-west-2:891376909120:function:sc-product-test-empty-lambda-LambdaFunction-NX8tjZ3sq0PX
  #     KmsKeyId: 31dc9883-64a5-43f9-86b4-ef0f929e3343
  #     NotifyAfterUnusedForDays: 90
  #     DeletionPolicy: Delete
  #     UpdateReplacePolicy: Delete
  #     System: taskcat-abc123
  #   template: ./service_catalog_portfolios/storage/secrets-manager/template.yaml