general:
  s3_bucket: "di-central-sre-build-taskcat"
  regions:
   - eu-west-2
  artifact_regions:
    - eu-west-2
  tags:
      TestingFramework: taskcat-<hash-place-holder>

project:
  owner: di-central-sre-build
  name: security-hub-template-tests
  package_lambda: false
  
tests:

  # messaging
  ## SNS you need to do twice once for FIFO and once for normal

  # storage

  ## dynamodb
  


  test-dynamodb:
    parameters:
      DynamoTableName: Taskcat-<hash-place-holder>-table
      TableKMSKey: bdfc7df5-95ae-426b-b520-80c3d434ae52
      System: taskcat-<hash-place-holder> 
    template: ./service_catalog_portfolios/storage/template.yaml

  ## s3
  test-s3:
    parameters:
      S3BucketName: taskcat-<hash-place-holder>-secret
      SecretDescription: "A secret tested by taskcat"
      System: taskcat-<hash-place-holder> 
    template: ./service_catalog_portfolios/storage/elb-access-logs-bucket.yaml



  # for s3 the environemnt needs to be dev
  # there are two files to test
  # s3 path is ./service_catalog_portfolios/storage/
  test-s3-logging:
    parameters:
      S3BucketName: taskcat-<hash-place-holder>-secret
      SecretDescription: "A secret tested by taskcat"
      System: taskcat-<hash-place-holder>
    template: ./service_catalog_portfolios/storage/s3/s3-logging-bucket.yaml

  
  ## secrets manager
  test-secrets-manager:
    parameters:
      SecretName: taskcat-<hash-place-holder>-secret
      SecretDescription: "A secret tested by taskcat"
      KeyRotationLambdaARN: arn:aws:lambda:eu-west-2:891376909120:function:sc-product-test-empty-lambda-LambdaFunction-AZvc5k0e2IhP
      KmsKeyId: bdfc7df5-95ae-426b-b520-80c3d434ae52
      NotifyAfterUnusedForDays: 90
    template: ./service_catalog_portfolios/storage/secrets-manager/template.yaml