Transform: AWS::Serverless-2016-10-31
Description: >
  # This Security Group template is for Security Group Ingress rules and Security Group Egress Global rules,
  # allowing inbound traffic from vpc cidr to port 443 and allowing outbound rules permitting instances to recieve traffic anywhere globally via port -1. 
  # This is set at default of port 443 and Ip Protocol of tcp.
  # Managed by: central-sre.

Parameters:
  VpcId:
    Type: String
    Description: List of Vpc Ids for Security Group 

  VpcCidr:
    Type: String
    Description: List of Vpc Cidr for Security Group

  FromPort:
    Type: Number
    Description: Allows inbound HTTPS traffic from Port 443
    Default: 443

  IpProtocol:
    Type: String
    Description: Enables data communications over networks 
    Default: tcp

  ToPort:
    Type: Number
    Description: Allows outbound HTTPS traffic via Port 443
    Default: 443


Resources:
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: This acts as a virtual firewall for your EC2 instances to control incoming and outgoing traffic for Lambda Security group ruleset
      SecurityGroupIngress:
        - CidrIp:
            !Ref VpcCidr
          Description: Adds ingress rule to security groups which permits instances to recieve traffic from vpc cidr to port 443
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
      SecurityGroupEgress: 
        - CidrIp: 0.0.0.0/0
          Description: Adds egress rule to security group which permits instances to receive traffic anywhere globally via port -1 with default of port 443
          FromPort: !Ref FromPort
          IpProtocol: !Ref IpProtocol
          ToPort: !Ref ToPort
      VpcId:
        !Ref VpcId 
      
Outputs:
  SecurityGroup: 
    Description: This is the Lambda functions Security Group ID
    Value: 
      !GetAtt LambdaSecurityGroup.GroupId