Transform: AWS::Serverless-2016-10-31
Description: >
  This Security Group template is for Security Group Ingress rules and Security Group Egress Global rules,
  Allowing inbound tcp traffic from vpc cidr range on port 443. Outbound rules can be configured, default of 443 and tcp. Set ToPort, FromPort and IpProtocol to -1 to allow all protocols and ports.
  Managed by: central-sre.

Parameters:
  VpcId:
    Type: String
    Description: Vpc Id for Security Group. 

  VpcCidr:
    Type: String
    Description: List of Vpc Cidr for Security Group

  FromPort:
    Type: Number
    Description: Configure the outbound from port, default of 443 set to -1 for all ports
    Default: 443

  IpProtocol:
    Type: String
    Description: Configure the outbound protocol, default of tcp, set to -1 for all protocols 
    Default: tcp

  ToPort:
    Type: Number
    Description: Configure the outbound to port, default of 443 set to -1 for all ports
    Default: 443


Resources:
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: This acts as a virtual firewall for your EC2 instances to control incoming and outgoing traffic for Lambda Security group ruleset
      SecurityGroupIngress:
        - CidrIp:
            !Ref VpcCidr
          Description: Adds ingress rule to security groups which permits instances to recieve traffic from vpc cidr to port 443
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
      SecurityGroupEgress: 
        - CidrIp: 0.0.0.0/0
          Description: Adds egress rule to security group which permits instances to send traffic anywhere for the configured ports and protocols.
          FromPort: !Ref FromPort
          IpProtocol: !Ref IpProtocol
          ToPort: !Ref ToPort
      VpcId:
        !Ref VpcId 
      
Outputs:
  SecurityGroup: 
    Description: The Lambda functions Security Group ID
    Value: 
      !GetAtt LambdaSecurityGroup.GroupId