AWSTemplateFormatVersion: "2010-09-09"

Description: >
  central-sre-security-hub-cfn s3-cloudformation template version: v0.0.1
  This template is to be used to create the S3 Logging Bucket for the AWS account.
  For any other S3 bucket you create, specify this bucket as the logging bucket.
  Out of the Box, when run in a non dev environment, this bucket will subscribe to the centralised logging bucket via SQS.
  ***************
  ** Important **
  ***************   
  ** Your bucket must be added to the subscription https://github.com/alphagov/centralised-security-logging-service/blob/bd306ca234e0cdeb6e6e1a7bf29d17dc56f86688/terraform/modules/csls-python-s3/locals.tf#L23 **
  ***************
  ** Important **
  ***************
  Enforces: security hub rule(s): S309, S310, S311, S312, S317, S318, S319
  Supports: security hub rule(s): S301, S302, S303, S304, S305, S306, S307, S308, S313, S314, S315, S316, S320, S321
  Managed by: central-sre.

Parameters: 

  S3BucketName: 
    Description: The name of the S3 bucket to create. 
    Type: String
    MinLength: 3
    MaxLength: 63

  Mode: 
    Description: S3 Object Lock retention mode.
    Type: String
    AllowedValues:
         - GOVERNANCE
         - COMPLIANCE
    Default: GOVERNANCE
  
  DeletionPolicy:
    Description: Cloudformation Deletion policy for the resources created by this template.
    Type: String
    AllowedValues:
      - Delete
      - Retain
    Default: Retain

  UpdateReplacePolicy:
    Description: Cloudformation Update Replace policy for the resources created by this template.
    Type: String
    AllowedValues:
      - Delete
      - Retain
    Default: Retain

  Product:
    Type: String
    Default: GOV.UK
    Description: "Tag all your resources with the product name."

  System:
    Type: String
    Default: Central-SRE-test-service
    Description: "Tag all your resources with the service name."

  Environment:
    Type: String
    Default: dev
    Description: "The name of the environment you are deploying into and the value for the tag environment to be added to all your resources."
    AllowedValues:
      - "dev"
      - "build"
      - "staging"
      - "integration"
      - "production"

  Owner:
    Type: String
    Default: Central-SRE
    Description: "Tag all your resources with the team name that owns the cloudfromation stack created with this template."

Conditions:
  CslsS3Logs:
    !Or [
      !Equals [!Ref Environment, production],
      !Equals [!Ref Environment, integration],
      !Equals [!Ref Environment, staging],
      !Equals [!Ref Environment, build]
    ]

Resources: 

  KMSKey:
    Type: AWS::KMS::Key
    DeletionPolicy: !Ref DeletionPolicy
    UpdateReplacePolicy: !Ref UpdateReplacePolicy
    Properties:
      Description: KMS key for encrypting the S3 logging bucket.
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::885513274347:role/csls_prodpython/csls_process_s3_logs_lambda_prodpython"
            Action: "kms:Decrypt"
            Resource: "*"
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "kms:Create*"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:Delete*"
              - "kms:ScheduleKeyDeletion"
              - "kms:CancelKeyDeletion"
            Resource: "*"
      Tags:
        - Key: StackName
          Value: !Sub "${AWS::StackName}"
        - Key: Product
          Value: !Ref Product
        - Key: System
          Value: !Ref System
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref Owner
        - Key: Source
          Value: "govuk-one-login/central-sre-security-hub-cfn/service_catalog_profiles/storage/s3/s3-logging-bucket.yaml"
  
  KMSKeyAlias:
    DeletionPolicy: !Ref DeletionPolicy
    UpdateReplacePolicy: !Ref UpdateReplacePolicy
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${S3BucketName}-kms-key"
      TargetKeyId: !Ref KMSKey
  
  S3Bucket: 
    Type: AWS::S3::Bucket
    # This is the logging bucket
    # checkov:skip=CKV_AWS_18     
    DeletionPolicy: !Ref DeletionPolicy
    UpdateReplacePolicy: !Ref UpdateReplacePolicy
    Properties:
      BucketName: !Ref S3BucketName
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption: 
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "aws:kms"
              KMSMasterKeyID: !Ref KMSKey
            BucketKeyEnabled: true
      ObjectLockEnabled: true
      ObjectLockConfiguration:
        ObjectLockEnabled: Enabled
        Rule:
          DefaultRetention:
            Mode: !Ref Mode
            Days: 30
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls: 
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      LifecycleConfiguration:
        Rules:
          - Id: BucketExpiry
            Status: Enabled
            ExpirationInDays: 30
      NotificationConfiguration:
        Fn::If: 
          - CslsS3Logs
          - QueueConfigurations: 
              - Event: "s3:ObjectCreated:*"
                Queue: arn:aws:sqs:eu-west-2:885513274347:cyber-security-s3-to-splunk-prodpython
          - Ref: AWS::NoValue
      Tags:
        - Key: StackName
          Value: !Sub "${AWS::StackName}"
        - Key: Product
          Value: !Ref Product
        - Key: System
          Value: !Ref System
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref Owner
        - Key: Source
          Value: "govuk-one-login/central-sre-security-hub-cfn/service_catalog_profiles/storage/s3/s3-logging-bucket.yaml"

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: !Ref DeletionPolicy
    UpdateReplacePolicy: !Ref UpdateReplacePolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowSSLRequestsOnly
            Action: s3:*
            Effect: Deny
            Principal: "*"
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref S3Bucket
                - "/*"
            Condition:
              Bool:
                aws:SecureTransport: false
          - Sid: EnforceTLSv12orHigher
            Action: s3:*
            Effect: Deny
            Principal: "*"
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref S3Bucket
                - "/*"
            Condition:
              NumericLessThan:
                s3:TlsVersion: 1.2
          - Action:
              - "s3:PutObject"
            Effect: Allow
            Principal:
              Service: logging.s3.amazonaws.com
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref S3Bucket
                - "/*"
            Condition:
              StringEquals:
                "aws:SourceAccount": !Sub "${AWS::AccountId}"
          - Fn::If:
            - CslsS3Logs
            - Sid: S3LogShipping
              Effect: Allow
              Resource:
                - !Sub ${S3Bucket.Arn}
                - !Sub ${S3Bucket.Arn}/*
              Principal:
                AWS: "arn:aws:iam::885513274347:role/csls_prodpython/csls_process_s3_logs_lambda_prodpython"
              Action:
                - s3:ListBucket
                - s3:GetObject
            - Ref: AWS::NoValue

Outputs:
  S3BucketNameOutput:
    Value: !Ref S3Bucket
    Description: The name of the Logging s3 bucket.