AWSTemplateFormatVersion: "2010-09-09"
Description: >
  central-sre-security-hub-cfn sns template version: v0.0.1
  Enforces: security hub rule(s) 
  - SNS01
  - SNS02
  Managed by: central-sre.
  
Parameters:
  TopicName:
    Description: The name of the SNS topic that will be deployed.
    Default: "null"
    Type: String
  
  FifoEnabled:
    Description: "Do you want to enable FIFO (first in, first out ordering) mode for this topic? [true, false]"
    Default: false
    Type: String
    AllowedValues:
       - true
       - false
  
  KMSKeyId:
    Description: "It is mandatory to provide a KMS key ID to encrypt this topic at rest. This ID must exist in the account which you are deploying to."
    Type: String

  MessageRetention:
    Description: "Number of days SNS retains messages. Can be between 1 - 365 days."
    Default: 30
    Type: Number
    MinValue: 1
    MaxValue: 365
  
  ContentBasedDeduplicationEnabled:
    Description: "Do you want to enable Content based deduplication for this topic? [true, false]"
    Default: false
    Type: String
    AllowedValues:
       - true
       - false

  SuccessfulLoggingPercent:
    Description: "How often do you want to log to cloudwatch your successful message delivery?"
    Type: String
    Default: "100"
    AllowedPattern: "[0-9]+"
    ConstraintDescription: "Please enter a valid number between 0 and 100."
    MaxLength: 3
    MinLength: 1

  # PublisherType:
  #   Description: "What aws resource type do you want as your publisher?"
  #   Default: "lambda"
  #   Type: String
  #   AllowedValues:
  #        - "sqs"
  #        - "lambda"
  #        - "firehose"
  #        - "application"

  # PublisherArn:
  #   Description: What is the arn of the resource that you want to publish to the sns topic? This must be a valid arn for SQS, Lambda, Application endpoint, or Firehose.
  #   Type: String
  #   AllowedPattern: "^arn:aws:[a-z0-9-]+:[a-z0-9-]+:[a-z0-9-]+:[0-9]+:[a-zA-Z0-9-_/]+"
  #   ConstraintDescription: Please enter a valid AWS ARN.

  SubscriberType:
    Description: "What aws resource type do you want as your subscriber?"
    Default: "lambda"
    Type: String
    AllowedValues:
         - "sqs"
         - "lambda"
         - "firehose"
         - "application"

  SubscriberArn:
    Description: What is the arn of the resource that you want to subscribe to the sns topic? This must be a valid arn for SQS, Lambda, Application endpoint, or Firehose.
    Type: String
    AllowedPattern: "^arn:(aws[a-zA-Z-]*)?:[a-zA-Z0-9-]+:[a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1}:\d{12}:[a-zA-Z0-9-_]+"
    ConstraintDescription: Please enter a valid AWS ARN.
  
  Product:
    Type: String
    Default: GOV.UK
    Description: "Tag all your resources with the product name."

  System:
    Type: String
    Default: Central-SRE-test-service
    Description: "Tag all your resources with the service name."

  Environment:
    Type: String
    Default: dev
    Description: "Tag the environment to all your resources."

  Owner:
    Type: String
    Default: Central-SRE
    Description: "Tag all your resources with the team name."

Conditions:
  HasTopicName: !Not [!Equals ["null", !Ref TopicName]]

Resources:
  SNSTopic:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::SNS::Topic
    Properties:
      ArchivePolicy: !Ref MessageRetention
      ContentBasedDeduplication: !Ref ContentBasedDeduplicationEnabled
      #SNS.2
      DeliveryStatusLogging: 
        - Protocol: !Ref SubscriberType
          # FailureFeedbackRoleArn: !GetAtt LoggingRole.RoleArn
          # SuccessFeedbackRoleArn: !GetAtt LoggingRole.RoleArn
          SuccessFeedbackSampleRate: !Ref SuccessfulLoggingPercent
      DisplayName: !If [HasTopicName,!Ref TopicName, !Sub "${AWS::StackName}-topic"]
      FifoTopic: !Ref FifoEnabled
      KmsMasterKeyId: !Ref KMSKeyId
      Tags:
        - Key: StackName
          Value: !Sub "${AWS::StackName}"
        - Key: Product
          Value: !Ref Product
        - Key: System
          Value: !Ref System
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref Owner
        - Key: Source
          Value: "govuk-one-login/central-sre-security-hub-cfn/cloudformation/sns/template.yaml"
      TopicName: !If [HasTopicName,!Ref TopicName, !Sub "${AWS::StackName}-topic"]
      TracingConfig: Active

  # PublishPolicy:
  #   Type: AWS::SNS::TopicPolicy
  #   Properties:
  #     PolicyDocument:
  #       Id: !Sub "${SNSTopic}-publish-policy"
  #       Version: '2012-10-17'
  #       Statement:
  #       - Effect: Allow
  #         Principal:
  #           Service: !Sub "${PublisherType}.amazonaws.com"
  #         Action: sns:Publish
  #         Resource: !Ref SNSTopic
  #         Condition:
  #             ArnEquals:
  #               aws:SourceArn: !Ref PublisherArn
  #     Topics: 
  #       - !Ref SNSTopic

  SubscribePolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: !Sub "${SNSTopic}-subscribe-policy"
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub "${SubscriberType}.amazonaws.com"
            Action: "sns:Subscribe"
            Resource: !Ref SNSTopic
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref SubscriberArn
      Topics: 
        - !Ref SNSTopic

  LoggingRole: 
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "sns.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - 
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - 
              Effect: Allow
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:PutMetricFilter
              - logs:PutRetentionPolicy
              Resource:
              - "*"

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: "Mandatory Tags"
        Parameters: 
          - Product
          - System
          - Environment
          - Owner
      - Label:
          default: "Subscription Configuration"
        Parameters: 
          - SubscriberType
          - SubscriberArn
      # - Label:
      #     default: "Publisher Configuration"
      #   Parameters: 
      #     - PublisherType
      #     - PublisherArn
  