AWSTemplateFormatVersion: "2010-09-09"
Description: >
  central-sre-security-hub-cfn sns template version: v0.0.1
  Enforces: security hub rule(s) 
  - SNS01
  - SNS02
  Managed by: central-sre.
  
Parameters:
  TopicName:
    Description: The name of the SNS topic that will be deployed.
    Default: "null"
    Type: String
  
  FifoEnabled:
    Description: "Do you want to enable FIFO (first in, first out ordering) mode for this topic? [true, false]"
    Default: false
    Type: String
    AllowedValues:
       - true
       - false
  
  KMSKeyId:
    Description: "It is mandatory to provide a KMS key ID to encrypt this topic at rest. This ID must exist in the account which you are deploying to."
    Type: String

  SuccessfulLoggingPercent:
    Description: "How often do you want to log to cloudwatch your successful message delivery?"
    Type: String
    Default: "100"
    AllowedPattern: "[0-9]+"
    ConstraintDescription: "Please enter a valid number between 0 and 100."
    MaxLength: 3
    MinLength: 1

  PublisherEnabled:
    Description: "Do you want to enable a Publisher for this topic?"
    Default: false
    Type: String
    AllowedValues:
       - true
       - false

  PublisherType:
    Description: "What aws resource type do you want as your publisher?"
    Type: String
    Default: "lambda"
    AllowedValues:
         - "sqs"
         - "lambda"
         - "firehose"
         - "application"

  PublisherArn:
    Description: What is the arn of the resource that you want to publish to the sns topic? This must be a valid arn for SQS, Lambda, Application endpoint, or Firehose.
    Type: String
    Default: "arn:aws:service:eu-west-2:000000000000:name"
    AllowedPattern: "arn:aws:[a-z0-9-]+:[a-z0-9-]+:[0-9]{12}:[a-z0-9-]+"
    ConstraintDescription: Please enter a valid AWS ARN.

  SubscriberEnabled:
    Description: "Do you want to enable a Subscriber for this topic?"
    Default: false
    Type: String
    AllowedValues:
       - true
       - false

  SubscriberType:
    Description: "What aws resource type do you want as your subscriber?"
    Type: String
    Default: "lambda"
    AllowedValues:
         - "sqs"
         - "lambda"
         - "firehose"
         - "application"

  SubscriberArn:
    Description: What is the arn of the resource that you want to subscribe to the sns topic? This must be a valid arn for SQS, Lambda, Application endpoint, or Firehose.
    Type: String
    Default: "arn:aws:service:eu-west-2:000000000000:name"
    AllowedPattern: "arn:aws:[a-z0-9-]+:[a-z0-9-]+:[0-9]{12}:[a-z0-9-]+"
    ConstraintDescription: Please enter a valid AWS ARN.

  XrayActiveTracing:
    Description: "Would you like to enable X-Ray active tracing? (Active or PassThrough)"
    Default: "PassThrough"
    Type: String
    ConstraintDescription: "Valid options are Active and PassThrough"
    AllowedValues:
         - "PassThrough"
         - "Active"
  
  Product:
    Type: String
    Default: GOV.UK
    Description: "Tag all your resources with the product name."

  System:
    Type: String
    Default: Central-SRE-test-service
    Description: "Tag all your resources with the service name."

  Environment:
    Type: String
    Default: dev
    Description: "Tag the environment to all your resources."

  Owner:
    Type: String
    Default: Central-SRE
    Description: "Tag all your resources with the team name."

Conditions:
  HasTopicName: !Not [!Equals ["null", !Ref TopicName]]
  HasFifo: !Equals [true, !Ref FifoEnabled]
  HasPublisher: !Equals [true, !Ref PublisherEnabled]
  HasSubscriber: !Equals [true, !Ref SubscriberEnabled]

Resources:
  SNSTopic:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::SNS::Topic
    Properties:
      FifoTopic: !Ref FifoEnabled
      ContentBasedDeduplication: !If [HasFifo, true, !Ref "AWS::NoValue"]
      #SNS.2
      DeliveryStatusLogging: 
        - Protocol: !Ref SubscriberType
          FailureFeedbackRoleArn: !GetAtt LoggingRole.Arn
          SuccessFeedbackRoleArn: !GetAtt LoggingRole.Arn
          SuccessFeedbackSampleRate: !Ref SuccessfulLoggingPercent
      DisplayName: !If [HasTopicName,!Ref TopicName, !Sub "${AWS::StackName}-topic"]
      
      KmsMasterKeyId: !Ref KMSKeyId
      Tags:
        - Key: StackName
          Value: !Sub "${AWS::StackName}"
        - Key: Product
          Value: !Ref Product
        - Key: System
          Value: !Ref System
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref Owner
        - Key: Source
          Value: "govuk-one-login/central-sre-security-hub-cfn/cloudformation/sns/template.yaml"
      TopicName: !If [HasTopicName,!Ref TopicName, !Sub "${AWS::StackName}-topic"]
      TracingConfig: !Ref XrayActiveTracing

  PublishPolicy:
    Condition: HasPublisher
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: !Sub "${SNSTopic}-publish-policy"
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: !Sub "${PublisherType}.amazonaws.com"
          Action: sns:Publish
          Resource: !Ref SNSTopic
          Condition:
              ArnEquals:
                aws:SourceArn: !Ref PublisherArn
      Topics: 
        - !Ref SNSTopic

  SubscribePolicy:
    Condition: HasSubscriber
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: !Sub "${SNSTopic}-subscribe-policy"
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub "${SubscriberType}.amazonaws.com"
            Action: "sns:Subscribe"
            Resource: !Ref SNSTopic
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref SubscriberArn
      Topics: 
        - !Ref SNSTopic

  LoggingRole: 
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "sns.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - 
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - 
              Effect: Allow
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:PutMetricFilter
              - logs:PutRetentionPolicy
              Resource:
              - "*"

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: "Mandatory Tags"
        Parameters: 
          - Product
          - System
          - Environment
          - Owner
      - Label:
          default: "Fifo Configuration"
        Parameters:
          - FifoEnabled
      - Label:
          default: "Subscription Configuration"
        Parameters: 
          - SubscriberEnabled
          - SubscriberType
          - SubscriberArn
      - Label:
          default: "Publisher Configuration"
        Parameters: 
          - PublisherEnabled
          - PublisherType
          - PublisherArn