AWSTemplateFormatVersion: "2010-09-09"

Description: >
  central-sre-security-hub-cfn secrets-manager template version: v0.0.1
  Enforces: security hub rule(s) SCRTS01, SCRTS03, SCRTS05.
  Supports: security hub rule(s) SCRTS04. 
  Managed by: central-sre.

Parameters:
  SecretName:
    Description: The secret name.
    Type: String

  SecretDescription:
    Description: The secret description.
    Type: String

  PeriodicRotationDays:
    Description: The number of days between rotations of this secret.
    Type: Number
    MaxValue: 90
    MinValue: 1
    Default: 90
    ConstraintDescription: All secrets must be set to rotate periodically, within a maximum of 90 days.
  
  KeyRotationLambdaARN:
    Description: ARN of the lambda function that will handle rotation of this secret.
    Type: String
    AllowedPattern: "arn:aws:lambda:.*"
    ConstraintDescription: Must be a valid AWS Lambda ARN

  KmsKeyId:
    Description: The Id of the KMS key to use for encryption.
    Type: String
    AllowedPattern: "^[0-9a-fA-F]{8}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{12}$"
    ConstraintDescription: Must be a valid KMS key Id (uuid format)

  NotifyAfterUnusedForDays:
    Description: > 
      Secrets that have not been used for 90 days will be marked as non-compliant.
      Use this with your rotation lambda to identify unused secrets so you can remove them from your stacks.
    Type: Number
    MaxValue: 90
    MinValue: 1
    Default: 90
    ConstraintDescription: Must be a value between 1 and 90.

  Product:
    Type: String
    Default: GOV.UK
    Description: "Tag all your resources with the product name."

  System:
    Type: String
    Default: Central-SRE-test-service
    Description: "Tag all your resources with the service name."

  Owner:
    Type: String
    Default: Central-SRE
    Description: "Tag all your resources with the team name."

  Environment:
    Type: String
    Default: dev
    Description: "The name of the environment you are deploying into and the value for the tag environment to be added to all your resources."
    AllowedValues:
      - "dev"
      - "build"
      - "staging"
      - "integration"
      - "production"
      
Resources: 
  SecretsManagerSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: !Ref SecretDescription
      KmsKeyId: !Ref KmsKeyId
      Name: !Ref SecretName
      Tags:
        - Key: StackName
          Value: !Ref AWS::StackName
        - Key: Name
          Value: !Ref SecretName
        - Key: Product
          Value: !Ref Product
        - Key: System
          Value: !Ref System
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref Owner
        - Key: Source
          Value: "govuk-one-login/central-sre-security-hub-cfn/service_catalog_profiles/storage/secrets-manager/template.yaml"
        - Key: NotifyAfterUnusedForDays
          Value: !Ref NotifyAfterUnusedForDays
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
      
  SecretsManagerRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    Properties:
      RotateImmediatelyOnUpdate: true
      RotationLambdaARN: !Ref KeyRotationLambdaARN
      SecretId: !GetAtt SecretsManagerSecret.Id
      RotationRules:
          AutomaticallyAfterDays: !Ref PeriodicRotationDays

  SecretsManagerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref KeyRotationLambdaARN
      Action: lambda:InvokeFunction
      Principal: secretsmanager.amazonaws.com
      SourceAccount: !Ref "AWS::AccountId"