name: PR To Main
# When a PR is opened, synchronize, or reopened this workflow will run.
# Make sure the service catalog templates are checkov and security hub complaint.
# Taskcat validates and   

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE }}
          aws-region: eu-west-2
      
      - name: Validate CloudFormation templates
        run: |
          for f in $(find ./service_catalog_portfolios -name '*.yaml')
          do
            echo 
            aws cloudformation validate-template --template-body file://$f
          done
      
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: service_catalog_portfolios/
          quiet: true 
          skip_check: CKV_AWS_111,CKV_AWS_173,CKV_AWS_158,CKV_AWS_27
          framework: cloudformation
      
      - name: Generate and apply hash
        run: |
          hash=$(tr -dc 'a-z0-9' </dev/urandom | head -c 13; echo)
          echo $hash
          sed -i "s/<hash-place-holder>/$hash/g" .taskcat.yml
          sed -i "s/<hash-place-holder>/$hash/g" build/scripts/run_taskcat.sh

      - name: Install TaskCat
        run: |
          pip install taskcat

      - name: Run TaskCat
        run: |
          ./build/scripts/run_taskcat.sh

