name: PR To Main - Integration

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: |
          echo "It was me!!"