name: Lint and AWS CloudFormation Validate

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.18'

    - name: Install cfn-lint
      run: |
        pip install cfn-lint

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.GH_ACTIONS_ROLE }}
        aws-region: eu-west-2


    - name: Run cfn-lint to check for issues
      run: |
        cfn-lint cloudformation/secrets-manager/template.yaml

    - name: Validate AWS CloudFormation stack
      run: |
        aws cloudformation validate-template \
          --template-body file://cloudformation/secrets-manager/template.yaml