name: Lint and AWS CloudFormation Validate

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE }}
          aws-region: eu-west-2
      
      # TODO removed for speed
      # - name: Validate AWS CloudFormation stack
      #   run: |
      #     aws cloudformation validate-template \
      #       --template-body file://service_catalog_portfolios/storage/secrets-manager/template.yaml
      
      - name: Generate and apply has
        run: |
          hash=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 13; echo)
          echo $hash
          sed -i "s\<hash-place-holder>\$hash}\g" input.txt

      - name: Install TaskCat
        run: |
          pip install taskcat

      - name: Run TaskCat
        run: |
          taskcat test run --no-delete       