AWSTemplateFormatVersion: "2010-09-09"

Description: >
  central-sre-security-hub-cfn secrets-manager template version: v0.0.1
  Enforces: security hub rules SCRTS01, SCRTS03, SCRTS05. 
  Managed by: central-sre.

Parameters:
  SecretName:
    Description: The secret name.
    Type: String

  SecretDescription:
    Description: The secret description.
    Type: String

  PeriodicRotationDays:
    Description: The number of days between rotations of this secret.
    Type: Number
    MaxValue: 90
    MinValue: 1
    Default: 90
    ConstraintDescription: All secrets must be set to rotate periodically, within a maximum of 90 days.
  
  KeyRotationLambdaARN:
    Description: ARN of the lambda function that will handle rotation of this secret.
    Type: String
    AllowedPattern: "arn:aws:lambda:.*"
    ConstraintDescription: Must be a valid AWS Lambda ARN

  KmsKeyId:
    Description: The Id of the KMS key to use for encryption.
    Type: String
    AllowedPattern: "^[0-9a-fA-F]{8}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{12}$"
    ConstraintDescription: Must be a valid KMS key Id (uuid format)
      
Resources: 
  SecretsManagerSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: !Ref SecretDescription
      KmsKeyId: !Ref KmsKeyId
      Name: !Ref SecretName
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
      
  SecretsManagerRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    Properties:
      RotateImmediatelyOnUpdate: true
      RotationLambdaARN: !Ref KeyRotationLambdaARN
      SecretId: !GetAtt SecretsManagerSecret.Id
      RotationRules:
          AutomaticallyAfterDays: !Ref PeriodicRotationDays

  SecretsManagerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref KeyRotationLambdaARN
      Action: lambda:InvokeFunction
      Principal: secretsmanager.amazonaws.com


